# Generated by Django 4.2.19 on 2025-02-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('degree', models.CharField(choices=[('ASIR', 'ASIR'), ('DAW', 'DAW'), ('DAM', 'DAM')], max_length=100)),
            ],
        ),
    ]
