# Generated by Django 4.2.19 on 2025-02-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('web_server', models.CharField(choices=[('apache', 'Apache'), ('nginx', 'Nginx'), ('iis', 'IIS')], max_length=10)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('engineer', 'Engineer'), ('manager', 'Manager'), ('guest', 'Guest')], max_length=10)),
                ('sso_options', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
