# Generated by Django 4.2.19 on 2025-02-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('engineer', 'Engineer'), ('manager', 'Manager'), ('guest', 'Guest')], default='guest', max_length=10),
        ),
    ]
